services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - 8081:8081
      - 5000:5000
    restart: always
    volumes:
      - nexus_data:/nexus-data
    networks:
      - local-default

volumes:
  nexus_data:

networks:
  local-default:
    external: true