services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-default

volumes:
  postgres_data:

networks:
  local-default:
    external: true