services:
  scouter-server:
    image: localhost:5000/spring/scouter-server:2.20.0
    container_name: scouter-server
    ports:
      - 6100:6100
      - 6100:6100/udp
      - 6180:6180
    restart: no
    volumes:
      - scouter_data:/app/data
    environment:
      - SC_SERVER_ID=SCCOUTER-COLLECTOR 
      - NET_HTTP_SERVER_ENABLED=true
      - NET_HTTP_API_SWAGGER_ENABLED=true
      - NET_HTTP_API_ENABLED=true
      - MGR_PURGE_PROFILE_KEEP_DAYS=2
      - MGR_PURGE_XLOG_KEEP_DAYS=2
      - MGR_PURGE_COUNTER_KEEP_DAYS=2
      - JAVA_OPT=-Xms512m -Xmx512m
    networks:
      - local-default

volumes:
  scouter_data:

networks:
  local-default:
    external: true